# pH i trendsjöar {.unnumbered}


```{r}
#| include: false

# function for importing excel files into R
import_slu_mvm_data_excel <- function(filename, numeric_var = NA, bad_quality_na = TRUE, sheet = 2){ 
  # numeric var: the first column with measured numeric variables
  
  # function for replacing values at the detection limit with half values
  replace_less_than_var <- function(values, bad_quality_na){ 
    values_parsed <- values %>% as.character() %>% parse_number(locale = locale(decimal_mark = ","))

    which_intervals <- which(substring(values,1,1) == "[")
    which_less_than <- which(substring(values,1,1) == "<")
    if (length(which_less_than) > 0) {
      values_less_than_half <- values[which_less_than] %>% gsub(",", ".", .) %>% gsub("<","",.) %>% as.numeric()
      values_parsed[which_less_than] <- values_less_than_half/2
    }

    if (bad_quality_na == TRUE) {
      values_parsed[which_intervals] <- NA
    } else {
      values_intervals <- values[which_intervals] %>%
        gsub("\\[","", .) %>%
        gsub("\\]","", .) %>%
        gsub(",",".", .) %>%
        as.numeric()
      values_parsed[which_intervals] <- values_intervals
    }

    return(values_parsed)
  }

  if (is.na(numeric_var) == TRUE) {
    stop("Supply the column index of first measured numeric variable")
  }
  
  out <- suppressWarnings(read_excel(filename, sheet = sheet, guess_max = 50000))
  
  out <- mutate_at(out, c(numeric_var:ncol(out)),
                   replace_less_than_var,
                   bad_quality_na = bad_quality_na)
                   
  out <- mutate_at(out, c(1:(numeric_var - 1)),
                   (function(x) {
                      x %>%
                        as.character() %>%
                        parse_guess(locale = locale(decimal_mark = ","))
                    }))
}

source("Z:\\my documents\\konsultationer\\Sara Sandström\\sourcecode_screening2024_season.R")

```

```{r}
#| include: false

library(mgcv)
library(tidyverse)
library(readxl)
library(lubridate)
library(janitor)
library(knitr)
library(ape)
library(ggpubr)
library(scrutiny)
library(rlang)
```
```{r}
#| include: false

sjöar_kemi2011 <- import_slu_mvm_data_excel("trend_kemi2011.xlsx", numeric_var = 31, sheet = 2)
sjöar_kemi2011$`Nationellt övervakningsstations-ID` <- sjöar_kemi2011$`Nationellt övervakningsstations-ID` %>% as.character()

sjöar_kemi2021 <- import_slu_mvm_data_excel("trend_kemi_efter2011.xlsx", numeric_var = 31, sheet = 2)
sjöar_kemi2021$`Nationellt övervakningsstations-ID` <- sjöar_kemi2021$`Nationellt övervakningsstations-ID` %>% as.character()

sjöar_kemi <- sjöar_kemi2011 %>% full_join(sjöar_kemi2021)
```


```{r}
#| message: false
#| warning: false
#| echo: false

sjöar_kemi_data1 <- sjöar_kemi %>% 
  clean_names() %>%
  mutate(
    si_mg_l = case_when(si_mg_l <= 0.5 ~ 0.25, TRUE ~ si_mg_l),
    cl_mg_l = case_when(cl_mg_l <= 0.25 ~ 0.125, TRUE ~ cl_mg_l), 
    zn_mg_l = case_when(zn_mg_l <= 0.5 ~ 0.25, TRUE ~ zn_mg_l),
    v_mg_l  = case_when(v_mg_l <= 0.03 ~ 0.015, TRUE ~ v_mg_l),
    pb_mg_l = case_when(pb_mg_l <= 0.02 ~ 0.01, TRUE ~ pb_mg_l),
    mn_mg_l = case_when(mn_mg_l <= 0.5 ~ 0.25, TRUE ~ mn_mg_l),
    ni_mg_l = case_when(ni_mg_l <= 0.05 ~ 0.025, TRUE ~ ni_mg_l),
    fe_mg_l = case_when(fe_mg_l <= 10 ~ 5, TRUE ~ fe_mg_l),
    f_mg_l  = case_when(f_mg_l <= 0.05 ~ 0.025, TRUE ~ f_mg_l),
    cu_mg_l = case_when(cu_mg_l < 0.04 ~ 0.02, TRUE ~ cu_mg_l),
    cr_mg_l = case_when(cr_mg_l <= 0.05 ~ 0.025, TRUE ~ cr_mg_l),
    co_mg_l = case_when(co_mg_l <= 0.01 ~ 0.005, TRUE ~ co_mg_l),
    cd_mg_l = case_when(cd_mg_l <= 0.006 ~ 0.003, TRUE ~ cd_mg_l),
    as_mg_l = case_when(as_mg_l <= 0.003 ~ 0.0015, TRUE ~ as_mg_l),
    k_mg_l  = case_when(k_mg_l <= 0.04 ~ 0.02, TRUE ~ k_mg_l),
    al_mg_l = case_when(al_mg_l < 5 ~ 2.5, TRUE ~ al_mg_l),
    nh4_n_mg_l_n = case_when(nh4_n_mg_l_n <= 4 ~ 2, TRUE ~ nh4_n_mg_l_n),
    no2_no3_n_mg_l_n = case_when(no2_no3_n_mg_l_n <= 3 ~ 1.5, TRUE ~ no2_no3_n_mg_l_n),
    toc_mg_l_c = case_when(toc_mg_l_c <= 0.05 ~ 0.025, TRUE ~ toc_mg_l_c),
    totn = case_when(tot_n_t_nb_mg_l_n <= 50 ~ 25, TRUE ~ tot_n_t_nb_mg_l_n),
    totp = case_when(tot_p_mg_l_p <= 1 ~ 0.5, TRUE ~ tot_p_mg_l_p),
    absf = case_when(abs_f_420_5cm <= 0.01 ~ 0.005, TRUE ~ abs_f_420_5cm),
    so4_ic_mg_l_s = case_when(so4_ic_mg_l_s <= 0.16 ~ 0.08, TRUE ~ so4_ic_mg_l_s),
    so4_ic_mg_l_so4 = case_when(so4_ic_mg_l_so4 <= 0.48 ~ 0.24, TRUE ~ so4_ic_mg_l_so4),
    DIN = nh4_n_mg_l_n + no2_no3_n_mg_l_n,
    BC  = ca_mg_l + mg_mg_l + na_mg_l + k_mg_l,
    SO4_komb = case_when(
      !is.na(so4_ic_mg_l_s) ~ so4_ic_mg_l_s / ((32.06) / 2), 
      !is.na(so4_ic_mg_l_so4) ~ so4_ic_mg_l_so4 / ((32.06 + 4 * 16) / 2)
    ),
    TotN_tnb = ifelse((provtagningsar + (provtagningsmanad - 1) / 12) > (2009 + 8 / 12), tot_n_t_nb_mg_l_n, NA),
    TotN = TotN_tnb %>% 
      coalesce(kjeld_n_mg_l_n + no2_no3_n_mg_l_n) %>% 
      coalesce(tot_n_ps_mg_l_n),
    siktdjup = siktdjup_med_kikare_m %>% 
      coalesce(siktdjup_utan_kikare_m) %>% 
      coalesce(siktdjup_m),
    si_mg_l = si_mg_l * 1000,
    VJA = 10^(-p_h) # Vätejonaktivitet
  ) %>% 
  group_by(overvakningsstation, nationellt_overvakningsstations_id, eu_id, provdatum) %>% 
  filter(max_provdjup_m <= 2, max_provdjup_m == min(max_provdjup_m)) %>%
  ungroup() %>%
  mutate(season = provtagningsmanad %>% 
           factor() %>% 
           fct_collapse("1" = c("1", "2", "12"),
                        "2" = c("3", "4", "5"),
                        "3" = c("6", "7", "8"),
                        "4" = c("9", "10", "11")) %>% 
           as.character() %>% 
           parse_number())
```

```{r}
#| message: false
#| warning: false
#| echo: false

screening_sjö <- sjöar_kemi_data1 %>%
  select(nationellt_overvakningsstations_id, provdatum, season, p_h) %>%
  drop_na(p_h) %>%
  group_by(nationellt_overvakningsstations_id) %>% 
  filter(n() > 60) %>%
  pivot_longer(cols = c("p_h")) %>% 
  screeningmodeling(values = value,
                    datevar = provdatum, 
                    seas = season, 
                    link = "identity", 
                    conf.type = "conf",
                    conf.level = 0.95,
                    beep = TRUE, 
                    tdist = FALSE,
                    autocor = TRUE,
                    nationellt_overvakningsstations_id)
```

```{r}
#| message: false
#| warning: false
#| echo: false

screening_sjö1 <- screening_sjö %>% 
  left_join(sjöar_kemi_data1 %>% 
              select(overvakningsstation, nationellt_overvakningsstations_id, stationskoordinat_e_y, stationskoordinat_n_x) %>%
              unique()) %>%
  filter(is.na(intercept) == FALSE)

# Screening plot
screening_sjö1 %>% plot_screeningtrends(y_id = nationellt_overvakningsstations_id, sorting = desc(stationskoordinat_n_x))
```
```{r}
#| message: false
#| warning: false
#| echo: false

single <- screening_sjö1 %>% arrange(desc(stationskoordinat_n_x)) %>% select(nationellt_overvakningsstations_id)
stationer <- single$nationellt_overvakningsstations_id %>% unique()

single_names <- screening_sjö1 %>% arrange(desc(stationskoordinat_n_x)) %>% select(overvakningsstation)
stationsnamn <- single_names$overvakningsstation

for (i in 1:NROW(stationer)) {
  singleplot <- screening_sjö1 %>% 
    filter(nationellt_overvakningsstations_id == stationer[i]) %>% 
    plot_individual_trend(title = stationsnamn[i])
  print(singleplot)
}
```

